export const projects = [{
    id: 1,
    title: "FitTrack",
    subtitle: "A Complete Fitness Management Platform",
    desc: "A full-stack Fitness Tracker Platform built with the MERN stack (MongoDB, Express.js, React.js, Node.js). Empowers users to track fitness progress, book trainers, join classes, and engage with a community.",
    link: "https://fitness-tracker-d03b6.web.app/",
    images: [
      "/assets/fitnessTracker.png",
      "/assets/fitnessTracker1.png",
      "/assets/fitnessTracker2.png",
    ],
    stack: ["MongoDB", "Express.js", "React.js", "Node.js", "Tailwind CSS", "Stripe"],
    difficulty: "Managing role-based dashboards and payment method while integrating real-time class scheduling.",
    futurePlan: "Add AI-based fitness recommendations and a social feed for progress sharing.",
  },

  {
    id: 2,
    title: "Plant Pal",
    subtitle: "Smart Plant Monitoring Platform",
    desc: "A platform that enables users to track daily plant care tasks, set reminders, and maintain health records for each plant.",
    link: "https://plant-track-4558e.web.app/",
    images: [
      "/assets/Plant-Track.png",
      "/assets/Plant-Track2.png",
      "/assets/Plant-Track3.png",
    ],
    stack: ["React.js", "Firebase", "Tailwind CSS", "React Router"],
    difficulty: "Handling managing databse and CRUD functionality with cloud data sync.",
    futurePlan: "Introduce IoT integration for live soil moisture tracking and watering automation.",
  },

  {
    id: 3,
    title: "Find a Doctor",
    subtitle: "DocTalk BD – Health Consultation Platform",
    desc: "A responsive healthcare platform connecting patients with doctors for quick online consultations.",
    link: "https://doc-talk-bd-by-zawad.netlify.app/home",
    images: [
      "/assets/Doctor-phudu.jpg",
      "/assets/Doctor2.png",
      "/assets/Doctor3.png",
    ],
    stack: ["React.js", "Firebase", "Tailwind CSS", "Express.js"],
    difficulty: "Implementing secure user authentication and managing dynamic appointment scheduling.",
    futurePlan: "Add video consultation features and an AI symptom checker.",
  },

  {
    id: 4,
    title: "English Janala",
    subtitle: "An Interactive English Learning Platform",
    desc: "A modern web platform that helps users practice English grammar, listening, and speaking with structured lessons and quizzes.",
    link: "https://english-janala-by-zawad.netlify.app/",
    images: [
      "/assets/EnglishJanala.png",
      "/assets/EnglishJanala2.png",
      "/assets/EnglishJanala3.png",
    ],
    stack: ["React.js", "Firebase", "Tailwind CSS"],
    difficulty: "Designing quiz logic and user progress tracking while maintaining smooth UI performance.",
    futurePlan: "Add gamification, leaderboards, and personalized lesson recommendations.",
  },

  {
    id: 5,
    title: "NextGenBlog",
    subtitle: "NextGenBlog – Modern Blogging Platform",
    desc: "NextGenBlog is a full-stack, user-friendly blogging platform that allows users to create, explore, and manage blogs with secure authentication and interactive features.",
    link: "https://blog-e084f.web.app/",
    images: [
      "/assets/blog1.png",
      "/assets/blog2.png",
      "/assets/blog3.png",
    ],
    stack: ["React.js", "Firebase", "MongoDB", "Express.js", "Tailwind CSS", "JWT"],
    difficulty: "Implementing secure JWT-based private routes, real-time wishlist and commenting system, and optimizing MongoDB text search with category filtering.",
    futurePlan: "Add AI-powered content recommendations, author analytics dashboard, and rich-text editor for advanced blog writing.",
  },
];